; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jun 24 2020 16:15:46 GMT-0700 (Pacific Daylight Time (Mexico))
; ================================================================================

DATAL5L7JK8YU4A:
	dc.w $0, DATAL5L7JK8YU4A_1-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_2-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_3-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_4-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_5-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_6-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_7-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_8-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_9-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_A-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_B-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_C-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_D-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_E-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_F-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_10-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_11-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_12-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_13-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_14-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_15-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_16-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_17-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_18-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_19-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_1A-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_1B-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_1C-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_1D-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_1E-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_1F-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_20-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_21-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_22-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_23-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_24-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_25-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_26-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_27-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_28-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_29-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_2A-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_2B-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_2C-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_2D-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_2E-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_2F-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_30-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_31-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_32-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_33-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_34-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_35-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_36-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_37-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_38-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_39-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_3A-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_3B-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_3C-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_3D-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_3E-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_3F-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_40-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_41-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_42-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_43-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_44-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_45-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_46-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_47-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_48-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_49-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_4A-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_4B-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_4C-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_4D-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_4E-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_4F-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_50-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_51-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_52-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_53-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_54-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_55-DATAL5L7JK8YU4A
	dc.w DATAL5L7JK8YU4A_56-DATAL5L7JK8YU4A, DATAL5L7JK8YU4A_57-DATAL5L7JK8YU4A
DATAL5L7JK8YU4A_1: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAL5L7JK8YU4A_2: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAL5L7JK8YU4A_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAL5L7JK8YU4A_4: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAL5L7JK8YU4A_5: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F0
	dc.b $C, $8, $0, $C, $F8
DATAL5L7JK8YU4A_6: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAL5L7JK8YU4A_7: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAL5L7JK8YU4A_8: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAL5L7JK8YU4A_9: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAL5L7JK8YU4A_A: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
DATAL5L7JK8YU4A_B: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATAL5L7JK8YU4A_C: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATAL5L7JK8YU4A_D: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATAL5L7JK8YU4A_E: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATAL5L7JK8YU4A_F: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATAL5L7JK8YU4A_10: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATAL5L7JK8YU4A_11: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATAL5L7JK8YU4A_12: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATAL5L7JK8YU4A_13: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $EC, $9, $0, $6, $FB
	dc.b $FC, $4, $0, $C, $FB
	dc.b $4, $9, $0, $E, $FB
DATAL5L7JK8YU4A_14: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATAL5L7JK8YU4A_15: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $EC, $0, $0, $8, $FD
	dc.b $F4, $A, $0, $9, $FD
DATAL5L7JK8YU4A_16: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
DATAL5L7JK8YU4A_17: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
DATAL5L7JK8YU4A_18: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
DATAL5L7JK8YU4A_19: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
DATAL5L7JK8YU4A_1A: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
DATAL5L7JK8YU4A_1B: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
DATAL5L7JK8YU4A_1C: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAL5L7JK8YU4A_1D: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAL5L7JK8YU4A_1E: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAL5L7JK8YU4A_1F: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAL5L7JK8YU4A_20: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATAL5L7JK8YU4A_21: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAL5L7JK8YU4A_22: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATAL5L7JK8YU4A_23: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAL5L7JK8YU4A_24: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAL5L7JK8YU4A_25: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAL5L7JK8YU4A_26: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAL5L7JK8YU4A_27: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAL5L7JK8YU4A_28: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAL5L7JK8YU4A_29: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAL5L7JK8YU4A_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAL5L7JK8YU4A_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAL5L7JK8YU4A_2C: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAL5L7JK8YU4A_2D: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAL5L7JK8YU4A_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAL5L7JK8YU4A_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAL5L7JK8YU4A_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAL5L7JK8YU4A_31: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
DATAL5L7JK8YU4A_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAL5L7JK8YU4A_33: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAL5L7JK8YU4A_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAL5L7JK8YU4A_35: dc.b $2
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $E, $0, $6, $F0
DATAL5L7JK8YU4A_36: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
DATAL5L7JK8YU4A_37: dc.b $4
	dc.b $F4, $4, $0, $0, $FC
	dc.b $FC, $D, $0, $2, $F4
	dc.b $C, $8, $0, $A, $F4
	dc.b $4, $0, $0, $D, $EC
DATAL5L7JK8YU4A_38: dc.b $1
	dc.b $F0, $F, $0, $0, $E0
DATAL5L7JK8YU4A_39: dc.b $1
	dc.b $F0, $F, $0, $0, $E0
DATAL5L7JK8YU4A_3A: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAL5L7JK8YU4A_3B: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATAL5L7JK8YU4A_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
DATAL5L7JK8YU4A_3D: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAL5L7JK8YU4A_3E: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $4, $0, $C, $F8
	dc.b $10, $0, $0, $E, $F8
DATAL5L7JK8YU4A_3F: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAL5L7JK8YU4A_40: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAL5L7JK8YU4A_41: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAL5L7JK8YU4A_42: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAL5L7JK8YU4A_43: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAL5L7JK8YU4A_44: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAL5L7JK8YU4A_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAL5L7JK8YU4A_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAL5L7JK8YU4A_47: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
DATAL5L7JK8YU4A_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
DATAL5L7JK8YU4A_49: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
DATAL5L7JK8YU4A_4A: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAL5L7JK8YU4A_4B: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAL5L7JK8YU4A_4C: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
DATAL5L7JK8YU4A_4D: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
DATAL5L7JK8YU4A_4E: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAL5L7JK8YU4A_4F: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATAL5L7JK8YU4A_50: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATAL5L7JK8YU4A_51: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAL5L7JK8YU4A_52: dc.b $1
	dc.b $F4, $A, $0, $0, $F4
DATAL5L7JK8YU4A_53: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAL5L7JK8YU4A_54: dc.b $1
	dc.b $F0, $F, $8, $0, $F0
DATAL5L7JK8YU4A_55: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAL5L7JK8YU4A_56: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAL5L7JK8YU4A_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
	even